### ISSUE TITLE
Setup tegola static assets to be served (index.html and style.js)

### ISSUE THREAD

**Issue by jj0hns0n** [terranodo/geonode-live#6]
The tegola demo shortcut in the menu points to http://localhost/demo/tegola/ but this returns a django 404. http://localhost/tegola/demo/ can be setup to serve files by putting a `static` dir in `/usr/local/bin` next to the binary and the config.toml and copying/symlinking the files in `/var/www/html/demo/tegola/` there. Probably we should put these things somewhere other than `/usr/local/bin` though

**Comment by kalxas** [comment]
The files are already located in /var/www/html/demo/tegola
We just need to configure apache to serve that folder at /demo/tegola
